arch:
 - amd64
 - ppc64le
language: cpp
os:
 - linux
 - osx
before_script:
 - mkdir build
 - cd build
script:
 - cmake ..
 - make
 - ./cpuid-dump
 - ./isa-info
 - ./cpu-info
 - ./cache-info
 - ctest --verbose
